/-
Copyright (c) 2021 Jannis Limperg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jannis Limperg
-/
module

public import Lean.Data.Options

public section

open Lean

namespace CoAes

initialize Check.all : Lean.Option Bool ←
  Option.register `coaes.check.all
    { defValue := false
      descr := "(coaes) Enable all runtime checks. Individual checks can still be disabled." }

structure Check where
  toOption : Lean.Option Bool

namespace Check

def get (opts : Options) (opt : Check) : Bool :=
  if let some val := opt.toOption.get? opts then
    val
  else
    Check.all.get opts

def isEnabled [Monad m] [MonadOptions m] (opt : Check) : m Bool :=
  return opt.get (← getOptions)

def name (opt : Check) : Name :=
  opt.toOption.name

end Check

-- Inspired by `Lean.Data.Options`.
local macro "register_coaes_check_option" optName:ident descr:str : command =>
  `(initialize option : Lean.Option Bool ←
      Lean.Option.register $(quote $ `coaes.check ++ optName.getId)
        { defValue := false, descr := $descr }

    def $(mkIdent $ `Check ++ optName.getId) : CoAes.Check := ⟨option⟩)

register_coaes_check_option proofReconstruction
    "(coaes) Typecheck partial proof terms during proof reconstruction."

register_coaes_check_option tree
    "(coaes) Check search tree invariants after every iteration of the search loop. Quite expensive."

register_coaes_check_option rules
    "(coaes) Check that information reported by rules is correct."

register_coaes_check_option script
    "(coaes) Check that the tactic script generated by CoAes proves the goal. When this check is active, CoAes generates a tactic script even if the user did not request one."

register_coaes_check_option script.steps
    "(coaes) Check each step of the tactic script generated by CoAes. When this check is active, CoAes generates a tactic script even if the user did not request one."

end CoAes
